Migrate more targets into taskfile
Signed-off-by: Balazs Nemeth <bnemeth@redhat.com>

diff --git a/taskfile.yaml b/taskfile.yaml
--- a/taskfile.yaml
+++ b/taskfile.yaml
@@ -10,13 +10,20 @@ env:
 
 vars:
   DPU_OPERATOR_TEMP_DIR: /tmp/dpu-operator-tmp
+  DPU_OPERATOR_GO_CACHE: /tmp/dpu-operator-cache
   BINDIR: bin
+  BINDIR_ABS:
+    sh: if [[ "{{.BINDIR}}" = /* ]]; then echo "{{.BINDIR}}"; else echo "$(pwd)/{{.BINDIR}}"; fi
   REGISTRY:
     sh: hostname | sed 's/$/:5000/'
   ENVTEST_K8S_VERSION: 1.27.1
   KUSTOMIZE_VERSION: v5.6.0
   GINKGO_VERSION:
     sh: go list -m -f '{{"{{.Version}}"}}' github.com/onsi/ginkgo/v2 | sed 's/^v//'
+  CONTROLLER_TOOLS_VERSION: v0.15.0
+  SETUP_ENVTEST_VERSION: release-0.16
+  OPERATOR_SDK_VERSION: v1.37.0
+  OPM_VERSION: v1.23.0
 
 includes:
   images:
@@ -30,6 +37,9 @@ includes:
     flatten: true
   operator-sdk:
     taskfile: ./taskfiles/operator-sdk.yaml
+    flatten: true
+  proto:
+    taskfile: ./taskfiles/proto.yaml
     flatten: true
   
 tasks:
@@ -84,11 +94,13 @@ tasks:
         -output-file bin/local-images.yaml
       - cp config/dev/kustomization.yaml bin
   
+  ## Download envtest-setup locally if necessary
   envtest:
     status:
-      - test -f {{.BINDIR}}/setup-envtest
+      - test -s {{.BINDIR}}/setup-envtest
+      - ./{{.BINDIR}}/setup-envtest --help | head -1 | grep -q {{.SETUP_ENVTEST_VERSION}}
     cmds:
-      - make envtest
+      - GOBIN={{.BINDIR_ABS}} GOFLAGS='' go install sigs.k8s.io/controller-runtime/tools/setup-envtest@{{.SETUP_ENVTEST_VERSION}}
 
   deploy:
     deps:
@@ -127,7 +139,7 @@ tasks:
         NF_INGRESS_IP=10.20.30.2
         EXTERNAL_CLIENT_DEV=eno12409
         EXTERNAL_CLIENT_IP=10.20.30.100
-        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR}} -p path)"
+        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR_ABS}} -p path)"
         {{.BINDIR}}/ginkgo -coverprofile cover.out ./e2e_test/...
       - hack/traffic_flow_tests.sh
 
@@ -144,3 +156,105 @@ tasks:
       - task: build-image-all
       - task: undeploy
       - task: deploy
+
+  podman-check:
+    cmds:
+      - |
+        if which podman > /dev/null; then
+          echo "Podman is available"
+        else
+          echo "Error: Podman is not available"
+          exit 1
+        fi
+
+  ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
+  manifests:
+    deps:
+      - task: controller-gen
+    cmds:
+      - GOFLAGS='' {{.BINDIR}}/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
+
+  prow-ci-manifests-check:
+    cmds:
+      - |
+        changed_files=$(git diff --name-only)
+        for file in $changed_files; do
+          diff_output=$(git diff -- $file)
+          echo "$diff_output"
+        done
+        if [ -n "$changed_files" ]; then
+          echo "Please run 'make manifests', the following files changed: $changed_files"
+          exit 1
+        fi
+
+  ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
+  generate:
+    deps:
+      - task: controller-gen
+    cmds:
+      - GOFLAGS='' {{.BINDIR}}/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
+
+  fmt:
+    status:
+      - |
+        files=$(find . -name "*.go" -not -path "./vendor/*" -not -path "./dpu-api/vendor/*")
+        output=$(gofmt -d $files)
+        [ -z "$output" ]
+    cmds:
+      - go fmt ./...
+      - cd api && go fmt ./...
+
+  fmt-check:
+    cmds:
+      - |
+        files=$(find . -name "*.go" -not -path "./vendor/*" -not -path "./dpu-api/vendor/*")
+        output=$(gofmt -d $files)
+        [ -n "$output" ] && echo "$output"
+        [ -z "$output" ]
+
+  vet:
+    cmds:
+      - go vet ./...
+
+  ## Download controller-gen locally if necessary. If wrong version is installed, it will be overwritten.
+  controller-gen:
+    status:
+      - test -s {{.BINDIR}}/controller-gen
+      - ./{{.BINDIR}}/controller-gen --version | grep -q {{.CONTROLLER_TOOLS_VERSION}}
+    cmds:
+      - GOBIN={{.BINDIR_ABS}} GOFLAGS='' go install sigs.k8s.io/controller-tools/cmd/controller-gen@{{.CONTROLLER_TOOLS_VERSION}}
+
+  test:
+    deps:
+      - task: podman-check
+      - task: manifests
+      - task: generate
+      - task: fmt
+      - task: vet
+      - task: envtest
+      - task: ginkgo
+    cmds:
+      - >
+        FAST_TEST=false
+        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR_ABS}} -p path)"
+        timeout 30m {{.BINDIR}}/ginkgo --repeat 4 {{if .TEST_FOCUS}}-focus "{{.TEST_FOCUS}}" {{end}}-coverprofile cover.out ./internal/... ./pkgs/... ./api/v1/...
+
+  fast-test:
+    deps:
+      - task: envtest
+      - task: ginkgo
+    cmds:
+      - >
+        FAST_TEST=true
+        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR_ABS}} -p path)"
+        {{.BINDIR}}/ginkgo {{if .TEST_FOCUS}}-focus "{{.TEST_FOCUS}}" {{end}}-coverprofile cover.out ./internal/... ./pkgs/... ./api/v1/...
+
+  vendor:
+    cmds:
+      - |
+        for d in . dpu-api api tools ; do
+          if [ "$d" = . ] ; then
+            (cd "$d" && go mod vendor) || exit $? ;
+          fi ;
+          (cd "$d" && go mod tidy) || exit $? ;
+        done
